; Generated from locales/*.ftl (setup-* messages); do not edit.
; Regenerate: UPDATE_NSIS_STRINGS=1 cargo test -p usbnexus-i18n

LangString setup_role_client ${LANG_ENGLISH} "Use as a client"
LangString setup_role_server ${LANG_ENGLISH} "Use as a server"
LangString setup_role_web ${LANG_ENGLISH} "Web access"
LangString setup_roles_subtitle ${LANG_ENGLISH} "Choose what this computer will do."
LangString setup_roles_title ${LANG_ENGLISH} "How will you use USB Nexus?"
LangString setup_service_failed ${LANG_ENGLISH} "The USB Nexus service could not be set up. Details are in the installation log."
LangString setup_usbip_failed ${LANG_ENGLISH} "The usbip-win2 driver could not be installed. You can run the USB Nexus setup again later to retry."
LangString setup_usbip_install_note ${LANG_ENGLISH} "The usbip-win2 driver will also be installed. USB devices stop for a few seconds during the installation, and Windows must be restarted afterwards."
LangString setup_usbip_present_note ${LANG_ENGLISH} "The usbip-win2 driver is already installed on this computer."
LangString setup_usbip_update_note ${LANG_ENGLISH} "The installed usbip-win2 driver is too old and will be updated. USB devices stop for a few seconds during the installation, and Windows must be restarted afterwards."
LangString setup_web_access ${LANG_ENGLISH} "Access:"
LangString setup_web_local ${LANG_ENGLISH} "Only this computer"
LangString setup_web_network ${LANG_ENGLISH} "The whole network"
LangString setup_web_password ${LANG_ENGLISH} "Password:"
LangString setup_web_password_hint ${LANG_ENGLISH} "At least 8 characters."
LangString setup_web_password_keep ${LANG_ENGLISH} "At least 8 characters. Leave empty to keep the current password."
LangString setup_web_password_repeat ${LANG_ENGLISH} "Password (again):"
LangString setup_web_port ${LANG_ENGLISH} "Port:"
LangString setup_web_port_busy ${LANG_ENGLISH} "✗ This port is used by another program"
LangString setup_web_port_free ${LANG_ENGLISH} "✓ The port is available"
LangString setup_web_port_invalid ${LANG_ENGLISH} "✗ Enter a number between 1 and 65535"
LangString setup_web_subtitle ${LANG_ENGLISH} "Settings for managing this computer from a browser."
LangString setup_web_title ${LANG_ENGLISH} "Web interface"

LangString setup_role_client ${LANG_TURKISH} "İstemci olarak kullanacağım"
LangString setup_role_server ${LANG_TURKISH} "Sunucu olarak kullanacağım"
LangString setup_role_web ${LANG_TURKISH} "Web'den erişim olacak"
LangString setup_roles_subtitle ${LANG_TURKISH} "USB Nexus'u bu bilgisayarda nasıl kullanacağınızı seçin."
LangString setup_roles_title ${LANG_TURKISH} "Kullanım şekli"
LangString setup_service_failed ${LANG_TURKISH} "USB Nexus hizmeti kurulamadı. Ayrıntılar kurulum günlüğünde."
LangString setup_usbip_failed ${LANG_TURKISH} "usbip-win2 sürücüsü kurulamadı. Daha sonra USB Nexus kurulumunu yeniden çalıştırarak tekrar deneyebilirsiniz."
LangString setup_usbip_install_note ${LANG_TURKISH} "usbip-win2 sürücüsü de kurulacak. Kurulum sırasında USB cihazları birkaç saniye kesilir; ardından Windows'un yeniden başlatılması gerekir."
LangString setup_usbip_present_note ${LANG_TURKISH} "usbip-win2 sürücüsü bu bilgisayarda zaten kurulu."
LangString setup_usbip_update_note ${LANG_TURKISH} "Kurulu usbip-win2 sürücüsü çok eski, güncellenecek. Kurulum sırasında USB cihazları birkaç saniye kesilir; ardından Windows'un yeniden başlatılması gerekir."
LangString setup_web_access ${LANG_TURKISH} "Erişim:"
LangString setup_web_local ${LANG_TURKISH} "Yalnızca bu bilgisayar"
LangString setup_web_network ${LANG_TURKISH} "Tüm ağ"
LangString setup_web_password ${LANG_TURKISH} "Parola:"
LangString setup_web_password_hint ${LANG_TURKISH} "En az 8 karakter."
LangString setup_web_password_keep ${LANG_TURKISH} "En az 8 karakter. Boş bırakırsanız mevcut parola korunur."
LangString setup_web_password_repeat ${LANG_TURKISH} "Parola (tekrar):"
LangString setup_web_port ${LANG_TURKISH} "Port:"
LangString setup_web_port_busy ${LANG_TURKISH} "✗ Bu port başka bir program tarafından kullanılıyor"
LangString setup_web_port_free ${LANG_TURKISH} "✓ Port kullanılabilir"
LangString setup_web_port_invalid ${LANG_TURKISH} "✗ 1 ile 65535 arasında bir sayı girin"
LangString setup_web_subtitle ${LANG_TURKISH} "Bu bilgisayarı tarayıcıdan yönetmek için ayarlar."
LangString setup_web_title ${LANG_TURKISH} "Web arayüzü"
