; Generated from locales/*.ftl (setup-* messages); do not edit.
; Regenerate: UPDATE_NSIS_STRINGS=1 cargo test -p usbnexus-i18n

LangString setup_role_client ${LANG_ENGLISH} "Use as a client"
LangString setup_role_server ${LANG_ENGLISH} "Use as a server"
LangString setup_role_web ${LANG_ENGLISH} "Web access"
LangString setup_roles_subtitle ${LANG_ENGLISH} "Choose what this computer will do."
LangString setup_roles_title ${LANG_ENGLISH} "How will you use USB Nexus?"
LangString setup_service_failed ${LANG_ENGLISH} "The USB Nexus service could not be set up. Details are in the installation log."
LangString setup_usbip_failed ${LANG_ENGLISH} "The usbip-win2 driver could not be installed. You can run the USB Nexus setup again later to retry."
LangString setup_usbip_install_note ${LANG_ENGLISH} "The usbip-win2 driver will also be installed. USB devices stop for a few seconds during the installation, and Windows must be restarted afterwards."
LangString setup_usbip_present_note ${LANG_ENGLISH} "The usbip-win2 driver is already installed on this computer."
LangString setup_usbip_update_note ${LANG_ENGLISH} "The installed usbip-win2 driver is too old and will be updated. USB devices stop for a few seconds during the installation, and Windows must be restarted afterwards."
LangString setup_web_access ${LANG_ENGLISH} "Access:"
LangString setup_web_local ${LANG_ENGLISH} "Only this computer"
LangString setup_web_network ${LANG_ENGLISH} "The whole network"
LangString setup_web_password ${LANG_ENGLISH} "Password:"
LangString setup_web_password_hint ${LANG_ENGLISH} "At least 8 characters."
LangString setup_web_password_keep ${LANG_ENGLISH} "At least 8 characters. Leave empty to keep the current password."
LangString setup_web_password_repeat ${LANG_ENGLISH} "Password (again):"
LangString setup_web_port ${LANG_ENGLISH} "Port:"
LangString setup_web_port_busy ${LANG_ENGLISH} "✗ This port is used by another program"
LangString setup_web_port_free ${LANG_ENGLISH} "✓ The port is available"
LangString setup_web_port_invalid ${LANG_ENGLISH} "✗ Enter a number between 1 and 65535"
LangString setup_web_subtitle ${LANG_ENGLISH} "Settings for managing this computer from a browser."
LangString setup_web_title ${LANG_ENGLISH} "Web interface"

LangString setup_role_client ${LANG_TURKISH} "İstemci olarak kullanacağım"
LangString setup_role_server ${LANG_TURKISH} "Sunucu olarak kullanacağım"
LangString setup_role_web ${LANG_TURKISH} "Web'den erişim olacak"
LangString setup_roles_subtitle ${LANG_TURKISH} "USB Nexus'u bu bilgisayarda nasıl kullanacağınızı seçin."
LangString setup_roles_title ${LANG_TURKISH} "Kullanım şekli"
LangString setup_service_failed ${LANG_TURKISH} "USB Nexus hizmeti kurulamadı. Ayrıntılar kurulum günlüğünde."
LangString setup_usbip_failed ${LANG_TURKISH} "usbip-win2 sürücüsü kurulamadı. Daha sonra USB Nexus kurulumunu yeniden çalıştırarak tekrar deneyebilirsiniz."
LangString setup_usbip_install_note ${LANG_TURKISH} "usbip-win2 sürücüsü de kurulacak. Kurulum sırasında USB cihazları birkaç saniye kesilir; ardından Windows'un yeniden başlatılması gerekir."
LangString setup_usbip_present_note ${LANG_TURKISH} "usbip-win2 sürücüsü bu bilgisayarda zaten kurulu."
LangString setup_usbip_update_note ${LANG_TURKISH} "Kurulu usbip-win2 sürücüsü çok eski, güncellenecek. Kurulum sırasında USB cihazları birkaç saniye kesilir; ardından Windows'un yeniden başlatılması gerekir."
LangString setup_web_access ${LANG_TURKISH} "Erişim:"
LangString setup_web_local ${LANG_TURKISH} "Yalnızca bu bilgisayar"
LangString setup_web_network ${LANG_TURKISH} "Tüm ağ"
LangString setup_web_password ${LANG_TURKISH} "Parola:"
LangString setup_web_password_hint ${LANG_TURKISH} "En az 8 karakter."
LangString setup_web_password_keep ${LANG_TURKISH} "En az 8 karakter. Boş bırakırsanız mevcut parola korunur."
LangString setup_web_password_repeat ${LANG_TURKISH} "Parola (tekrar):"
LangString setup_web_port ${LANG_TURKISH} "Port:"
LangString setup_web_port_busy ${LANG_TURKISH} "✗ Bu port başka bir program tarafından kullanılıyor"
LangString setup_web_port_free ${LANG_TURKISH} "✓ Port kullanılabilir"
LangString setup_web_port_invalid ${LANG_TURKISH} "✗ 1 ile 65535 arasında bir sayı girin"
LangString setup_web_subtitle ${LANG_TURKISH} "Bu bilgisayarı tarayıcıdan yönetmek için ayarlar."
LangString setup_web_title ${LANG_TURKISH} "Web arayüzü"

LangString setup_role_client ${LANG_GERMAN} "Als Client verwenden"
LangString setup_role_server ${LANG_GERMAN} "Als Server verwenden"
LangString setup_role_web ${LANG_GERMAN} "Webzugriff"
LangString setup_roles_subtitle ${LANG_GERMAN} "Wählen Sie, was dieser Computer tun soll."
LangString setup_roles_title ${LANG_GERMAN} "Wie werden Sie USB Nexus verwenden?"
LangString setup_service_failed ${LANG_GERMAN} "Der USB-Nexus-Dienst konnte nicht eingerichtet werden. Details finden Sie im Installationsprotokoll."
LangString setup_usbip_failed ${LANG_GERMAN} "Der usbip-win2-Treiber konnte nicht installiert werden. Sie können das USB-Nexus-Setup später erneut ausführen, um es noch einmal zu versuchen."
LangString setup_usbip_install_note ${LANG_GERMAN} "Der usbip-win2-Treiber wird ebenfalls installiert. USB-Geräte pausieren während der Installation kurz, und Windows muss danach neu gestartet werden."
LangString setup_usbip_present_note ${LANG_GERMAN} "Der usbip-win2-Treiber ist auf diesem Computer bereits installiert."
LangString setup_usbip_update_note ${LANG_GERMAN} "Der installierte usbip-win2-Treiber ist zu alt und wird aktualisiert. USB-Geräte pausieren während der Installation kurz, und Windows muss danach neu gestartet werden."
LangString setup_web_access ${LANG_GERMAN} "Zugriff:"
LangString setup_web_local ${LANG_GERMAN} "Nur dieser Computer"
LangString setup_web_network ${LANG_GERMAN} "Das gesamte Netzwerk"
LangString setup_web_password ${LANG_GERMAN} "Kennwort:"
LangString setup_web_password_hint ${LANG_GERMAN} "Mindestens 8 Zeichen."
LangString setup_web_password_keep ${LANG_GERMAN} "Mindestens 8 Zeichen. Leer lassen, um das aktuelle Kennwort zu behalten."
LangString setup_web_password_repeat ${LANG_GERMAN} "Kennwort (Wiederholung):"
LangString setup_web_port ${LANG_GERMAN} "Port:"
LangString setup_web_port_busy ${LANG_GERMAN} "✗ Dieser Port wird von einem anderen Programm verwendet"
LangString setup_web_port_free ${LANG_GERMAN} "✓ Der Port ist verfügbar"
LangString setup_web_port_invalid ${LANG_GERMAN} "✗ Geben Sie eine Zahl zwischen 1 und 65535 ein"
LangString setup_web_subtitle ${LANG_GERMAN} "Einstellungen für die Verwaltung dieses Computers über einen Browser."
LangString setup_web_title ${LANG_GERMAN} "Weboberfläche"

LangString setup_role_client ${LANG_SPANISH} "Usar como cliente"
LangString setup_role_server ${LANG_SPANISH} "Usar como servidor"
LangString setup_role_web ${LANG_SPANISH} "Acceso web"
LangString setup_roles_subtitle ${LANG_SPANISH} "Elija lo que hará este equipo."
LangString setup_roles_title ${LANG_SPANISH} "¿Cómo va a usar USB Nexus?"
LangString setup_service_failed ${LANG_SPANISH} "No se pudo configurar el servicio de USB Nexus. Encontrará los detalles en el registro de instalación."
LangString setup_usbip_failed ${LANG_SPANISH} "No se pudo instalar el controlador usbip-win2. Puede volver a ejecutar la instalación de USB Nexus más adelante para reintentarlo."
LangString setup_usbip_install_note ${LANG_SPANISH} "También se instalará el controlador usbip-win2. Los dispositivos USB se detienen unos segundos durante la instalación y después hay que reiniciar Windows."
LangString setup_usbip_present_note ${LANG_SPANISH} "El controlador usbip-win2 ya está instalado en este equipo."
LangString setup_usbip_update_note ${LANG_SPANISH} "El controlador usbip-win2 instalado es demasiado antiguo y se actualizará. Los dispositivos USB se detienen unos segundos durante la instalación y después hay que reiniciar Windows."
LangString setup_web_access ${LANG_SPANISH} "Acceso:"
LangString setup_web_local ${LANG_SPANISH} "Solo este equipo"
LangString setup_web_network ${LANG_SPANISH} "Toda la red"
LangString setup_web_password ${LANG_SPANISH} "Contraseña:"
LangString setup_web_password_hint ${LANG_SPANISH} "Al menos 8 caracteres."
LangString setup_web_password_keep ${LANG_SPANISH} "Al menos 8 caracteres. Déjelo en blanco para conservar la contraseña actual."
LangString setup_web_password_repeat ${LANG_SPANISH} "Contraseña (de nuevo):"
LangString setup_web_port ${LANG_SPANISH} "Puerto:"
LangString setup_web_port_busy ${LANG_SPANISH} "✗ Este puerto lo está usando otro programa"
LangString setup_web_port_free ${LANG_SPANISH} "✓ El puerto está disponible"
LangString setup_web_port_invalid ${LANG_SPANISH} "✗ Introduzca un número entre 1 y 65535"
LangString setup_web_subtitle ${LANG_SPANISH} "Configuración para administrar este equipo desde un navegador."
LangString setup_web_title ${LANG_SPANISH} "Interfaz web"

LangString setup_role_client ${LANG_FRENCH} "Utiliser comme client"
LangString setup_role_server ${LANG_FRENCH} "Utiliser comme serveur"
LangString setup_role_web ${LANG_FRENCH} "Accès web"
LangString setup_roles_subtitle ${LANG_FRENCH} "Choisissez ce que cet ordinateur va faire."
LangString setup_roles_title ${LANG_FRENCH} "Comment allez-vous utiliser USB Nexus ?"
LangString setup_service_failed ${LANG_FRENCH} "Le service USB Nexus n'a pas pu être configuré. Les détails figurent dans le journal d'installation."
LangString setup_usbip_failed ${LANG_FRENCH} "Le pilote usbip-win2 n'a pas pu être installé. Vous pouvez relancer l'installation d'USB Nexus plus tard pour réessayer."
LangString setup_usbip_install_note ${LANG_FRENCH} "Le pilote usbip-win2 sera également installé. Les périphériques USB s'interrompent pendant quelques secondes durant l'installation, et Windows devra ensuite être redémarré."
LangString setup_usbip_present_note ${LANG_FRENCH} "Le pilote usbip-win2 est déjà installé sur cet ordinateur."
LangString setup_usbip_update_note ${LANG_FRENCH} "Le pilote usbip-win2 installé est trop ancien et sera mis à jour. Les périphériques USB s'interrompent pendant quelques secondes durant l'installation, et Windows devra ensuite être redémarré."
LangString setup_web_access ${LANG_FRENCH} "Accès :"
LangString setup_web_local ${LANG_FRENCH} "Cet ordinateur uniquement"
LangString setup_web_network ${LANG_FRENCH} "Tout le réseau"
LangString setup_web_password ${LANG_FRENCH} "Mot de passe :"
LangString setup_web_password_hint ${LANG_FRENCH} "Au moins 8 caractères."
LangString setup_web_password_keep ${LANG_FRENCH} "Au moins 8 caractères. Laissez vide pour conserver le mot de passe actuel."
LangString setup_web_password_repeat ${LANG_FRENCH} "Mot de passe (à nouveau) :"
LangString setup_web_port ${LANG_FRENCH} "Port :"
LangString setup_web_port_busy ${LANG_FRENCH} "✗ Ce port est utilisé par un autre programme"
LangString setup_web_port_free ${LANG_FRENCH} "✓ Le port est disponible"
LangString setup_web_port_invalid ${LANG_FRENCH} "✗ Entrez un nombre entre 1 et 65535"
LangString setup_web_subtitle ${LANG_FRENCH} "Paramètres pour gérer cet ordinateur depuis un navigateur."
LangString setup_web_title ${LANG_FRENCH} "Interface web"

LangString setup_role_client ${LANG_ITALIAN} "Usa come client"
LangString setup_role_server ${LANG_ITALIAN} "Usa come server"
LangString setup_role_web ${LANG_ITALIAN} "Accesso web"
LangString setup_roles_subtitle ${LANG_ITALIAN} "Scegli cosa farà questo computer."
LangString setup_roles_title ${LANG_ITALIAN} "Come vuoi usare USB Nexus?"
LangString setup_service_failed ${LANG_ITALIAN} "Non è stato possibile configurare il servizio USB Nexus. I dettagli sono nel registro di installazione."
LangString setup_usbip_failed ${LANG_ITALIAN} "Non è stato possibile installare il driver usbip-win2. Puoi eseguire di nuovo l'installazione di USB Nexus più tardi per riprovare."
LangString setup_usbip_install_note ${LANG_ITALIAN} "Verrà installato anche il driver usbip-win2. I dispositivi USB si interrompono per qualche secondo durante l'installazione e sarà necessario riavviare Windows in seguito."
LangString setup_usbip_present_note ${LANG_ITALIAN} "Il driver usbip-win2 è già installato su questo computer."
LangString setup_usbip_update_note ${LANG_ITALIAN} "Il driver usbip-win2 installato è troppo vecchio e verrà aggiornato. I dispositivi USB si interrompono per qualche secondo durante l'installazione e sarà necessario riavviare Windows in seguito."
LangString setup_web_access ${LANG_ITALIAN} "Accesso:"
LangString setup_web_local ${LANG_ITALIAN} "Solo questo computer"
LangString setup_web_network ${LANG_ITALIAN} "Tutta la rete"
LangString setup_web_password ${LANG_ITALIAN} "Password:"
LangString setup_web_password_hint ${LANG_ITALIAN} "Almeno 8 caratteri."
LangString setup_web_password_keep ${LANG_ITALIAN} "Almeno 8 caratteri. Lascia vuoto per mantenere la password attuale."
LangString setup_web_password_repeat ${LANG_ITALIAN} "Password (di nuovo):"
LangString setup_web_port ${LANG_ITALIAN} "Porta:"
LangString setup_web_port_busy ${LANG_ITALIAN} "✗ Questa porta è usata da un altro programma"
LangString setup_web_port_free ${LANG_ITALIAN} "✓ La porta è disponibile"
LangString setup_web_port_invalid ${LANG_ITALIAN} "✗ Inserire un numero tra 1 e 65535"
LangString setup_web_subtitle ${LANG_ITALIAN} "Impostazioni per gestire questo computer da un browser."
LangString setup_web_title ${LANG_ITALIAN} "Interfaccia web"

LangString setup_role_client ${LANG_PORTUGUESEBR} "Usar como cliente"
LangString setup_role_server ${LANG_PORTUGUESEBR} "Usar como servidor"
LangString setup_role_web ${LANG_PORTUGUESEBR} "Acesso pela web"
LangString setup_roles_subtitle ${LANG_PORTUGUESEBR} "Escolha o que este computador vai fazer."
LangString setup_roles_title ${LANG_PORTUGUESEBR} "Como você vai usar o USB Nexus?"
LangString setup_service_failed ${LANG_PORTUGUESEBR} "Não foi possível configurar o serviço USB Nexus. Os detalhes estão no log de instalação."
LangString setup_usbip_failed ${LANG_PORTUGUESEBR} "Não foi possível instalar o driver usbip-win2. Você pode executar a instalação do USB Nexus novamente mais tarde para tentar de novo."
LangString setup_usbip_install_note ${LANG_PORTUGUESEBR} "O driver usbip-win2 também será instalado. Os dispositivos USB param por alguns segundos durante a instalação, e o Windows precisará ser reiniciado depois."
LangString setup_usbip_present_note ${LANG_PORTUGUESEBR} "O driver usbip-win2 já está instalado neste computador."
LangString setup_usbip_update_note ${LANG_PORTUGUESEBR} "O driver usbip-win2 instalado está muito antigo e será atualizado. Os dispositivos USB param por alguns segundos durante a instalação, e o Windows precisará ser reiniciado depois."
LangString setup_web_access ${LANG_PORTUGUESEBR} "Acesso:"
LangString setup_web_local ${LANG_PORTUGUESEBR} "Somente este computador"
LangString setup_web_network ${LANG_PORTUGUESEBR} "Toda a rede"
LangString setup_web_password ${LANG_PORTUGUESEBR} "Senha:"
LangString setup_web_password_hint ${LANG_PORTUGUESEBR} "Pelo menos 8 caracteres."
LangString setup_web_password_keep ${LANG_PORTUGUESEBR} "Pelo menos 8 caracteres. Deixe em branco para manter a senha atual."
LangString setup_web_password_repeat ${LANG_PORTUGUESEBR} "Senha (novamente):"
LangString setup_web_port ${LANG_PORTUGUESEBR} "Porta:"
LangString setup_web_port_busy ${LANG_PORTUGUESEBR} "✗ Esta porta está sendo usada por outro programa"
LangString setup_web_port_free ${LANG_PORTUGUESEBR} "✓ A porta está disponível"
LangString setup_web_port_invalid ${LANG_PORTUGUESEBR} "✗ Digite um número entre 1 e 65535"
LangString setup_web_subtitle ${LANG_PORTUGUESEBR} "Configurações para gerenciar este computador a partir de um navegador."
LangString setup_web_title ${LANG_PORTUGUESEBR} "Interface web"

LangString setup_role_client ${LANG_RUSSIAN} "Использовать как клиент"
LangString setup_role_server ${LANG_RUSSIAN} "Использовать как сервер"
LangString setup_role_web ${LANG_RUSSIAN} "Веб-доступ"
LangString setup_roles_subtitle ${LANG_RUSSIAN} "Выберите, для чего будет служить этот компьютер."
LangString setup_roles_title ${LANG_RUSSIAN} "Как вы будете использовать USB Nexus?"
LangString setup_service_failed ${LANG_RUSSIAN} "Не удалось настроить службу USB Nexus. Подробности — в журнале установки."
LangString setup_usbip_failed ${LANG_RUSSIAN} "Не удалось установить драйвер usbip-win2. Вы можете повторить попытку позже, запустив установку USB Nexus снова."
LangString setup_usbip_install_note ${LANG_RUSSIAN} "Также будет установлен драйвер usbip-win2. Во время установки USB-устройства на несколько секунд перестанут работать, после чего потребуется перезагрузка Windows."
LangString setup_usbip_present_note ${LANG_RUSSIAN} "Драйвер usbip-win2 уже установлен на этом компьютере."
LangString setup_usbip_update_note ${LANG_RUSSIAN} "Установленный драйвер usbip-win2 слишком старый и будет обновлён. Во время установки USB-устройства на несколько секунд перестанут работать, после чего потребуется перезагрузка Windows."
LangString setup_web_access ${LANG_RUSSIAN} "Доступ:"
LangString setup_web_local ${LANG_RUSSIAN} "Только этот компьютер"
LangString setup_web_network ${LANG_RUSSIAN} "Вся сеть"
LangString setup_web_password ${LANG_RUSSIAN} "Пароль:"
LangString setup_web_password_hint ${LANG_RUSSIAN} "Не менее 8 символов."
LangString setup_web_password_keep ${LANG_RUSSIAN} "Не менее 8 символов. Оставьте пустым, чтобы сохранить текущий пароль."
LangString setup_web_password_repeat ${LANG_RUSSIAN} "Пароль (ещё раз):"
LangString setup_web_port ${LANG_RUSSIAN} "Порт:"
LangString setup_web_port_busy ${LANG_RUSSIAN} "✗ Этот порт занят другой программой"
LangString setup_web_port_free ${LANG_RUSSIAN} "✓ Порт свободен"
LangString setup_web_port_invalid ${LANG_RUSSIAN} "✗ Введите число от 1 до 65535"
LangString setup_web_subtitle ${LANG_RUSSIAN} "Настройки для управления этим компьютером из браузера."
LangString setup_web_title ${LANG_RUSSIAN} "Веб-интерфейс"

LangString setup_role_client ${LANG_JAPANESE} "クライアントとして使用する"
LangString setup_role_server ${LANG_JAPANESE} "サーバーとして使用する"
LangString setup_role_web ${LANG_JAPANESE} "Web アクセスを使用する"
LangString setup_roles_subtitle ${LANG_JAPANESE} "このコンピューターの用途を選択してください。"
LangString setup_roles_title ${LANG_JAPANESE} "USB Nexus をどのように使用しますか？"
LangString setup_service_failed ${LANG_JAPANESE} "USB Nexus サービスを設定できませんでした。詳細はインストールログを確認してください。"
LangString setup_usbip_failed ${LANG_JAPANESE} "usbip-win2 ドライバーをインストールできませんでした。後で USB Nexus のセットアップを再実行すると再試行できます。"
LangString setup_usbip_install_note ${LANG_JAPANESE} "usbip-win2 ドライバーも同時にインストールされます。インストール中は USB デバイスが数秒間停止し、その後 Windows の再起動が必要です。"
LangString setup_usbip_present_note ${LANG_JAPANESE} "usbip-win2 ドライバーはこのコンピューターに既にインストールされています。"
LangString setup_usbip_update_note ${LANG_JAPANESE} "インストール済みの usbip-win2 ドライバーが古すぎるため更新されます。インストール中は USB デバイスが数秒間停止し、その後 Windows の再起動が必要です。"
LangString setup_web_access ${LANG_JAPANESE} "アクセス："
LangString setup_web_local ${LANG_JAPANESE} "このコンピューターのみ"
LangString setup_web_network ${LANG_JAPANESE} "ネットワーク全体"
LangString setup_web_password ${LANG_JAPANESE} "パスワード："
LangString setup_web_password_hint ${LANG_JAPANESE} "8 文字以上。"
LangString setup_web_password_keep ${LANG_JAPANESE} "8 文字以上。空欄のままにすると現在のパスワードが維持されます。"
LangString setup_web_password_repeat ${LANG_JAPANESE} "パスワード（再入力）："
LangString setup_web_port ${LANG_JAPANESE} "ポート："
LangString setup_web_port_busy ${LANG_JAPANESE} "✗ このポートは他のプログラムが使用しています"
LangString setup_web_port_free ${LANG_JAPANESE} "✓ このポートは使用可能です"
LangString setup_web_port_invalid ${LANG_JAPANESE} "✗ 1 から 65535 までの数値を入力してください"
LangString setup_web_subtitle ${LANG_JAPANESE} "ブラウザーからこのコンピューターを管理するための設定です。"
LangString setup_web_title ${LANG_JAPANESE} "Web インターフェース"

LangString setup_role_client ${LANG_SIMPCHINESE} "用作客户端"
LangString setup_role_server ${LANG_SIMPCHINESE} "用作服务器"
LangString setup_role_web ${LANG_SIMPCHINESE} "网页访问"
LangString setup_roles_subtitle ${LANG_SIMPCHINESE} "请选择本计算机的用途。"
LangString setup_roles_title ${LANG_SIMPCHINESE} "您将如何使用 USB Nexus？"
LangString setup_service_failed ${LANG_SIMPCHINESE} "USB Nexus 服务设置失败。详情请查看安装日志。"
LangString setup_usbip_failed ${LANG_SIMPCHINESE} "usbip-win2 驱动程序安装失败。您可以稍后重新运行 USB Nexus 安装程序进行重试。"
LangString setup_usbip_install_note ${LANG_SIMPCHINESE} "同时会安装 usbip-win2 驱动程序。安装期间 USB 设备会中断几秒钟，之后需要重新启动 Windows。"
LangString setup_usbip_present_note ${LANG_SIMPCHINESE} "本计算机已安装 usbip-win2 驱动程序。"
LangString setup_usbip_update_note ${LANG_SIMPCHINESE} "已安装的 usbip-win2 驱动程序过旧，将进行更新。安装期间 USB 设备会中断几秒钟，之后需要重新启动 Windows。"
LangString setup_web_access ${LANG_SIMPCHINESE} "访问范围："
LangString setup_web_local ${LANG_SIMPCHINESE} "仅本计算机"
LangString setup_web_network ${LANG_SIMPCHINESE} "整个网络"
LangString setup_web_password ${LANG_SIMPCHINESE} "密码："
LangString setup_web_password_hint ${LANG_SIMPCHINESE} "至少 8 个字符。"
LangString setup_web_password_keep ${LANG_SIMPCHINESE} "至少 8 个字符。留空则保留当前密码。"
LangString setup_web_password_repeat ${LANG_SIMPCHINESE} "密码（再次输入）："
LangString setup_web_port ${LANG_SIMPCHINESE} "端口："
LangString setup_web_port_busy ${LANG_SIMPCHINESE} "✗ 该端口已被另一个程序占用"
LangString setup_web_port_free ${LANG_SIMPCHINESE} "✓ 该端口可用"
LangString setup_web_port_invalid ${LANG_SIMPCHINESE} "✗ 请输入 1 到 65535 之间的数字"
LangString setup_web_subtitle ${LANG_SIMPCHINESE} "用于从浏览器管理本计算机的设置。"
LangString setup_web_title ${LANG_SIMPCHINESE} "网页界面"
