#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
set -e
if [ -d /run/systemd/system ]; then
    systemctl daemon-reload || true
fi
if [ "$1" = "purge" ]; then
    rm -rf /var/lib/usbnexus
fi
exit 0
